"""PostgreSQL storage for shared Kanban boards.

Each board uses its own PostgreSQL schema.  The schema is derived from the
root Hermes database schema and the board's durable database id, so profiles
and worker processes share one board without weakening board isolation.
"""

from __future__ import annotations

import atexit
import contextlib
import hashlib
import re
import sqlite3
import threading
from contextlib import contextmanager
from pathlib import Path


KANBAN_POSTGRES_SCHEMA_VERSION = 1

KANBAN_TABLE_COLUMNS = {
    "tasks": (
        "id", "title", "body", "assignee", "status", "priority", "created_by",
        "created_at", "started_at", "completed_at", "workspace_kind", "workspace_path",
        "branch_name", "project_id", "claim_lock", "claim_expires", "tenant", "result",
        "idempotency_key", "consecutive_failures", "worker_pid", "last_failure_error",
        "max_runtime_seconds", "last_heartbeat_at", "current_run_id", "workflow_template_id",
        "current_step_key", "skills", "model_override", "provider_override", "reasoning_effort",
        "max_retries", "goal_mode", "goal_max_turns", "session_id", "block_kind",
        "block_recurrences", "completion_contract",
    ),
    "task_links": ("parent_id", "child_id"),
    "task_comments": ("id", "task_id", "author", "body", "created_at"),
    "task_events": ("id", "task_id", "run_id", "kind", "payload", "created_at"),
    "task_runs": (
        "id", "task_id", "profile", "step_key", "status", "claim_lock", "claim_expires",
        "worker_pid", "max_runtime_seconds", "last_heartbeat_at", "started_at", "ended_at",
        "outcome", "summary", "metadata", "error",
    ),
    "task_attachments": (
        "id", "task_id", "filename", "stored_path", "content_type", "size", "uploaded_by",
        "created_at",
    ),
    "kanban_notify_subs": (
        "task_id", "platform", "chat_id", "thread_id", "user_id", "user_id_alt", "chat_type",
        "notifier_profile", "delivery_mode", "delivery_metadata", "created_at", "last_event_id",
        "last_ping_event_id",
    ),
}

_IDENTITY_TABLES = ("task_comments", "task_events", "task_runs", "task_attachments")

KANBAN_POSTGRES_SCHEMA_SQL = """
CREATE TABLE tasks (
    id                   TEXT PRIMARY KEY,
    title                TEXT NOT NULL,
    body                 TEXT,
    assignee             TEXT,
    status               TEXT NOT NULL,
    priority             BIGINT DEFAULT 0,
    created_by           TEXT,
    created_at           BIGINT NOT NULL,
    started_at           BIGINT,
    completed_at         BIGINT,
    workspace_kind       TEXT NOT NULL DEFAULT 'scratch',
    workspace_path       TEXT,
    branch_name          TEXT,
    project_id           TEXT,
    claim_lock           TEXT,
    claim_expires        BIGINT,
    tenant               TEXT,
    result               TEXT,
    idempotency_key      TEXT,
    consecutive_failures BIGINT NOT NULL DEFAULT 0,
    worker_pid           BIGINT,
    last_failure_error   TEXT,
    max_runtime_seconds  BIGINT,
    last_heartbeat_at    BIGINT,
    current_run_id       BIGINT,
    workflow_template_id TEXT,
    current_step_key     TEXT,
    skills               TEXT,
    model_override       TEXT,
    provider_override    TEXT,
    reasoning_effort     TEXT,
    max_retries          BIGINT,
    goal_mode            BIGINT NOT NULL DEFAULT 0,
    goal_max_turns       BIGINT,
    session_id           TEXT,
    block_kind           TEXT,
    block_recurrences    BIGINT NOT NULL DEFAULT 0,
    completion_contract  TEXT
);

CREATE TABLE task_links (
    parent_id TEXT NOT NULL,
    child_id  TEXT NOT NULL,
    PRIMARY KEY (parent_id, child_id)
);

CREATE TABLE task_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE task_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    TEXT NOT NULL,
    run_id     BIGINT,
    kind       TEXT NOT NULL,
    payload    TEXT,
    created_at BIGINT NOT NULL
);

CREATE TABLE task_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             TEXT NOT NULL,
    profile             TEXT,
    step_key            TEXT,
    status              TEXT NOT NULL,
    claim_lock          TEXT,
    claim_expires       BIGINT,
    worker_pid          BIGINT,
    max_runtime_seconds BIGINT,
    last_heartbeat_at   BIGINT,
    started_at          BIGINT NOT NULL,
    ended_at            BIGINT,
    outcome             TEXT,
    summary             TEXT,
    metadata            TEXT,
    error               TEXT
);

CREATE TABLE task_attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      TEXT NOT NULL,
    filename     TEXT NOT NULL,
    stored_path  TEXT NOT NULL,
    content_type TEXT,
    size         BIGINT NOT NULL DEFAULT 0,
    uploaded_by  TEXT,
    created_at   BIGINT NOT NULL
);

CREATE TABLE kanban_notify_subs (
    task_id           TEXT NOT NULL,
    platform          TEXT NOT NULL,
    chat_id           TEXT NOT NULL,
    thread_id         TEXT NOT NULL DEFAULT '',
    user_id           TEXT,
    user_id_alt       TEXT,
    chat_type         TEXT,
    notifier_profile  TEXT,
    delivery_mode     TEXT NOT NULL DEFAULT 'notify',
    delivery_metadata TEXT,
    created_at        BIGINT NOT NULL,
    last_event_id     BIGINT NOT NULL DEFAULT 0,
    last_ping_event_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (task_id, platform, chat_id, thread_id)
);

CREATE INDEX idx_tasks_assignee_status ON tasks(assignee, status);
CREATE INDEX idx_tasks_status          ON tasks(status);
CREATE INDEX idx_tasks_tenant          ON tasks(tenant);
CREATE INDEX idx_tasks_idempotency     ON tasks(idempotency_key);
CREATE INDEX idx_tasks_session_id      ON tasks(session_id);
CREATE INDEX idx_links_child           ON task_links(child_id);
CREATE INDEX idx_links_parent          ON task_links(parent_id);
CREATE INDEX idx_comments_task         ON task_comments(task_id, created_at);
CREATE INDEX idx_events_task           ON task_events(task_id, created_at);
CREATE INDEX idx_events_run            ON task_events(run_id, id);
CREATE INDEX idx_runs_task             ON task_runs(task_id, started_at);
CREATE INDEX idx_runs_status           ON task_runs(status);
CREATE INDEX idx_attachments_task      ON task_attachments(task_id, created_at);
CREATE INDEX idx_notify_task           ON kanban_notify_subs(task_id);

CREATE TABLE kanban_schema_version (version BIGINT PRIMARY KEY);
INSERT INTO kanban_schema_version(version) VALUES (1);
"""


def database_settings():
    """Resolve the root-owned database used by every profile on the board."""
    from hermes_cli import kanban_db as kb
    from hermes_state_backend import resolve_database_settings

    return resolve_database_settings(kb.kanban_home() / "state.db")


def uses_postgres() -> bool:
    return database_settings().backend == "postgres"


def board_schema_name(base_schema: str, database_id: str) -> str:
    """Return a readable, collision-resistant PostgreSQL identifier."""
    readable = re.sub(r"[^a-z0-9_]", "_", database_id.lower())[:20] or "board"
    digest = hashlib.sha256(database_id.encode("utf-8")).hexdigest()[:10]
    suffix = f"_kanban_{readable}_{digest}"
    return base_schema[: 63 - len(suffix)] + suffix


def _board_identity(board: str | None) -> tuple[str, str]:
    from hermes_cli import kanban_db as kb

    slug = kb._normalize_board_slug(board) or kb.get_current_board()
    return slug, kb.board_database_id(slug)


def board_schema(board: str | None = None) -> str:
    settings = database_settings()
    if settings.backend != "postgres" or settings.schema is None:
        raise ValueError("Kanban PostgreSQL storage requires database.backend: postgres")
    _, database_id = _board_identity(board)
    return board_schema_name(settings.schema, database_id)


_POOL_LOCK = threading.RLock()
_POOLS: dict[tuple[str, str, bool], object] = {}
_INITIALIZED: set[tuple[str, str]] = set()


def _connection_kwargs() -> dict:
    from hermes_state_postgres import _row_factory

    return {
        "autocommit": True,
        "row_factory": _row_factory,
        "connect_timeout": 5,
        "application_name": "hermes-agent-kanban",
    }


def _initialize_schema(settings, schema: str, *, read_only: bool) -> None:
    import psycopg
    from psycopg import sql

    key = (settings.database_url, schema)
    if not read_only and key in _INITIALIZED:
        return
    with psycopg.connect(settings.database_url, **_connection_kwargs()) as connection:
        if connection.info.server_version < 170000:
            raise ValueError("PostgreSQL Kanban storage requires PostgreSQL 17 or later")
        if read_only:
            connection.execute(
                sql.SQL("SET search_path TO {}, pg_catalog").format(sql.Identifier(schema))
            )
            row = connection.execute(
                "SELECT to_regclass('kanban_schema_version')"
            ).fetchone()
            if row is None or row[0] is None:
                raise PermissionError(
                    "Kanban descendants require an initialized board; ask its owner to initialize it"
                )
            version = connection.execute(
                "SELECT version FROM kanban_schema_version"
            ).fetchone()[0]
            if version != KANBAN_POSTGRES_SCHEMA_VERSION:
                raise RuntimeError("PostgreSQL Kanban schema requires a writable upgrade")
            return

        with connection.transaction():
            connection.execute("SELECT set_config('lock_timeout', '5000', true)")
            connection.execute(
                "SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))", (schema,)
            )
            connection.execute(
                sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema))
            )
            connection.execute(
                sql.SQL("SET LOCAL search_path TO {}, pg_catalog").format(sql.Identifier(schema))
            )
            exists = connection.execute(
                "SELECT to_regclass('kanban_schema_version')"
            ).fetchone()[0]
            if exists is None:
                connection.execute(KANBAN_POSTGRES_SCHEMA_SQL)
            else:
                version = connection.execute(
                    "SELECT version FROM kanban_schema_version"
                ).fetchone()[0]
                if version != KANBAN_POSTGRES_SCHEMA_VERSION:
                    raise RuntimeError(
                        f"Unsupported PostgreSQL Kanban schema version {version}"
                    )
    _INITIALIZED.add(key)


def initialize_board(board: str | None = None) -> str:
    settings = database_settings()
    if settings.backend != "postgres" or settings.database_url is None:
        raise ValueError("Kanban PostgreSQL storage requires database.backend: postgres")
    schema = board_schema(board)
    with _POOL_LOCK:
        _initialize_schema(settings, schema, read_only=False)
    return schema


def _pool_for(settings, schema: str, *, read_only: bool):
    from psycopg import sql
    from psycopg_pool import ConnectionPool

    key = (settings.database_url, schema, read_only)
    with _POOL_LOCK:
        pool = _POOLS.get(key)
        if pool is not None:
            return pool
        _initialize_schema(settings, schema, read_only=read_only)

        def configure(connection):
            connection.execute(
                sql.SQL("SET search_path TO {}, pg_catalog").format(sql.Identifier(schema))
            )
            if read_only:
                connection.execute("SET default_transaction_read_only = on")

        pool = ConnectionPool(
            settings.database_url,
            kwargs=_connection_kwargs(),
            configure=configure,
            min_size=0,
            max_size=8,
            max_idle=60,
            timeout=5,
            open=True,
            name=f"kanban-{schema[-24:]}",
        )
        _POOLS[key] = pool
        return pool


_NULL_SAFE_PARAMETER = re.compile(r"\bIS\s+\?", re.IGNORECASE)


class KanbanPostgresConnection:
    """SQLite-shaped handle backed by one checked-out pooled connection."""

    backend = "postgres"

    def __init__(self, pool, schema: str, *, read_only: bool = False):
        self._pool = pool
        self._connection = pool.getconn(timeout=5)
        self.schema = schema
        self.read_only = read_only
        self._closed = False

    @property
    def in_transaction(self) -> bool:
        from psycopg.pq import TransactionStatus

        return self._connection.info.transaction_status != TransactionStatus.IDLE

    def execute(self, statement, params=()):
        from hermes_state_postgres import _bind_parameters

        statement = _NULL_SAFE_PARAMETER.sub("IS NOT DISTINCT FROM ?", statement)
        return self._connection.execute(_bind_parameters(statement), params)

    def executemany(self, statement, params):
        from hermes_state_postgres import _bind_parameters

        statement = _NULL_SAFE_PARAMETER.sub("IS NOT DISTINCT FROM ?", statement)
        with self._connection.cursor() as cursor:
            return cursor.executemany(_bind_parameters(statement), params)

    @contextmanager
    def transaction(self, *, read_only: bool = False, repeatable_read: bool = False):
        with self._connection.transaction():
            if read_only or repeatable_read:
                clauses = []
                if repeatable_read:
                    clauses.append("ISOLATION LEVEL REPEATABLE READ")
                if read_only:
                    clauses.append("READ ONLY")
                self._connection.execute("SET TRANSACTION " + " ".join(clauses))
            yield self

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self.in_transaction:
            with contextlib.suppress(Exception):
                self._connection.rollback()
        self._pool.putconn(self._connection)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        if self.in_transaction:
            if exc_type is None:
                self._connection.commit()
            else:
                self._connection.rollback()
        return False

    def __del__(self):
        with contextlib.suppress(Exception):
            self.close()


def connect(board: str | None = None, *, read_only: bool = False) -> KanbanPostgresConnection:
    settings = database_settings()
    if settings.backend != "postgres" or settings.database_url is None:
        raise ValueError("Kanban PostgreSQL storage requires database.backend: postgres")
    schema = board_schema(board)
    pool = _pool_for(settings, schema, read_only=read_only)
    return KanbanPostgresConnection(pool, schema, read_only=read_only)


def copy_sqlite_to_postgres(
    source_path: Path,
    target: KanbanPostgresConnection,
    *,
    batch_size: int = 1000,
) -> dict[str, int]:
    """Copy one SQLite board into an empty PostgreSQL board atomically."""
    if target.backend != "postgres" or target.read_only:
        raise ValueError("Migration requires a writable PostgreSQL Kanban connection")
    if batch_size < 1:
        raise ValueError("batch_size must be positive")
    source_path = source_path.expanduser().resolve()
    if not source_path.is_file():
        raise FileNotFoundError(f"Kanban SQLite database not found: {source_path}")

    from psycopg import sql
    from hermes_cli import kanban_db as kb

    source = sqlite3.connect(source_path.as_uri() + "?mode=ro", uri=True)
    source.row_factory = sqlite3.Row
    try:
        source.execute("BEGIN")
        if source.execute("PRAGMA quick_check").fetchone()[0] != "ok":
            raise ValueError(f"SQLite integrity check failed for {source_path}")
        available_tables = {
            row[0]
            for row in source.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
        missing_tables = set(KANBAN_TABLE_COLUMNS) - available_tables
        if missing_tables:
            raise ValueError(
                "SQLite board is missing tables: " + ", ".join(sorted(missing_tables))
            )

        counts: dict[str, int] = {}
        with kb.write_txn(target):
            raw = target._connection
            for table in KANBAN_TABLE_COLUMNS:
                if raw.execute(
                    sql.SQL("SELECT 1 FROM {} LIMIT 1").format(sql.Identifier(table))
                ).fetchone() is not None:
                    raise ValueError(
                        f"PostgreSQL table {table} is not empty; migration refused"
                    )

            for table, supported_columns in KANBAN_TABLE_COLUMNS.items():
                source_columns = tuple(
                    row[1] for row in source.execute(f'PRAGMA table_info("{table}")')
                )
                unsupported = set(source_columns) - set(supported_columns)
                if unsupported:
                    raise ValueError(
                        f"Unsupported {table} columns: {', '.join(sorted(unsupported))}"
                    )
                columns = tuple(column for column in supported_columns if column in source_columns)
                rows = source.execute(
                    f'SELECT {", ".join(columns)} FROM "{table}"'
                )
                copy_sql = sql.SQL("COPY {} ({}) FROM STDIN").format(
                    sql.Identifier(table),
                    sql.SQL(", ").join(map(sql.Identifier, columns)),
                )
                count = 0
                with raw.cursor() as cursor, cursor.copy(copy_sql) as copier:
                    while batch := rows.fetchmany(batch_size):
                        for row in batch:
                            copier.write_row(tuple(row[column] for column in columns))
                            count += 1
                counts[table] = count

            for table in _IDENTITY_TABLES:
                raw.execute(
                    f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                    f"COALESCE(MAX(id), 1), COUNT(*) > 0) FROM {table}"
                )
            for table, expected in counts.items():
                actual = raw.execute(
                    sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table))
                ).fetchone()[0]
                if actual != expected:
                    raise RuntimeError(
                        f"Row count mismatch for {table}: {expected} source, {actual} target"
                    )
        return counts
    finally:
        source.close()


def copy_postgres_to_sqlite(
    source: KanbanPostgresConnection,
    target_path: Path,
    *,
    batch_size: int = 1000,
) -> dict[str, int]:
    """Write a transactionally consistent PostgreSQL board snapshot as SQLite."""
    if source.backend != "postgres":
        raise ValueError("Source must be a PostgreSQL Kanban connection")
    if batch_size < 1:
        raise ValueError("batch_size must be positive")

    from hermes_cli import kanban_db as kb
    from hermes_cli import kanban_db_connect as kbc

    target = sqlite3.connect(target_path, isolation_level=None)
    target.row_factory = sqlite3.Row
    try:
        target.executescript(kb.SCHEMA_SQL)
        kbc._migrate_add_optional_columns(target)
        counts: dict[str, int] = {}
        target.execute("BEGIN IMMEDIATE")
        try:
            with source.transaction(read_only=True, repeatable_read=True):
                for table, columns in KANBAN_TABLE_COLUMNS.items():
                    column_sql = ", ".join(columns)
                    rows = source.execute(f"SELECT {column_sql} FROM {table}")
                    insert = (
                        f"INSERT INTO {table} ({column_sql}) VALUES "
                        f"({', '.join('?' for _ in columns)})"
                    )
                    count = 0
                    while batch := rows.fetchmany(batch_size):
                        target.executemany(
                            insert,
                            [tuple(row[column] for column in columns) for row in batch],
                        )
                        count += len(batch)
                    counts[table] = count
            target.execute("COMMIT")
        except Exception:
            with contextlib.suppress(sqlite3.Error):
                target.execute("ROLLBACK")
            raise
        return counts
    finally:
        target.close()


def storage_key(board: str | None = None) -> str:
    return f"postgres:{board_schema(board)}"


def drop_board(board: str) -> None:
    """Drop one deleted board's schema after closing its local pools."""
    import psycopg
    from psycopg import sql

    settings = database_settings()
    if settings.backend != "postgres" or settings.database_url is None:
        return
    schema = board_schema(board)
    with _POOL_LOCK:
        matching = [key for key in _POOLS if key[0] == settings.database_url and key[1] == schema]
        for key in matching:
            _POOLS.pop(key).close(timeout=5)
        _INITIALIZED.discard((settings.database_url, schema))
        with psycopg.connect(settings.database_url, **_connection_kwargs()) as connection:
            with connection.transaction():
                connection.execute(
                    "SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))", (schema,)
                )
                connection.execute(
                    sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(schema))
                )


def close_pools() -> None:
    with _POOL_LOCK:
        pools = list(_POOLS.values())
        _POOLS.clear()
        _INITIALIZED.clear()
    for pool in pools:
        with contextlib.suppress(Exception):
            pool.close(timeout=1)


atexit.register(close_pools)
